2011-03-01 16:53:14: (log.c.166) server started 
2011-03-01 16:53:18,264 X.X.X.X         |INFO| |||||||||||||||||||||||||||||||||||| SERVER START ||||||||||||||||||||||||||||||||||||||||||| <main.py:33>
2011-03-01 16:53:18,293 X.X.X.X         |INFO| Debug: True <main.py:36>
2011-03-01 16:53:18,294 X.X.X.X         |INFO| CONFIG: {'instance': 'GAM2', 'beanstalk': {'port': 11238, 'address': '0.0.0.0'}, 'memcache': {'port': 11222, 'address': '0.0.0.0'}, 'database': {'host': 'localhost', 'password': 'ringwrathes', 'db': 'gam2', 'user': 'root', 'dbn': 'mysql'}, 'default_host': 'http://ec2-204-236-198-80.compute-1.amazonaws.com/', 'email': {'username': 'myimapaccount@gmail.com', 'host': 'smtp.gmail.com', 'password': 'mypwd', 'port': 587}, 'dev': True} <main.py:37>
2011-03-01 16:53:22,189 127.0.0.1       |INFO| ---------- GET / -------------------------------------------------------------------------- <controller.py:32>
2011-03-01 16:53:22,276 127.0.0.1       |INFO| Connected to db: <lib.web.db.MySQLDB instance at 0x10127cb48> <controller.py:28>
2011-03-01 16:53:22,277 127.0.0.1       |INFO| SESSION: <Storage {'ip': u'127.0.0.1', 'session_id': 'f4da8a05a7c9c6626ae97c8f109f7602685d952d'}>  <controller.py:42>
2011-03-01 16:53:22: (mod_fastcgi.c.2701) FastCGI-stderr: Traceback (most recent call last):
  File "/Users/ethanholda/Sites/gam2/lib/web/application.py", line 242, in process
    return self.handle()
  File "/Users/ethanholda/Sites/gam2/lib/web/application.py", line 233, in handle
    return self._delegate(fn, self.fvars, args)
  File "/Users/ethanholda/Sites/gam2/lib/web/application.py", line 412, in _delegate
    return handle_class(cls)
  File "/Users/ethanholda/Sites/gam2/lib/web/application.py", line 387, in handle_class
    return tocall(*args)
TypeError: GET() takes at most 2 arguments (3 given)

 
2011-03-01 16:53:52,939 127.0.0.1       |INFO| ---------- GET / -------------------------------------------------------------------------- <controller.py:32>
2011-03-01 16:53:52,939 127.0.0.1       |INFO| SESSION: <Storage {'ip': u'127.0.0.1', 'session_id': 'f4da8a05a7c9c6626ae97c8f109f7602685d952d', '_changed': False}>  <controller.py:42>
2011-03-01 16:53:52: (mod_fastcgi.c.2701) FastCGI-stderr: Traceback (most recent call last):
  File "/Users/ethanholda/Sites/gam2/lib/web/application.py", line 242, in process
    return self.handle()
  File "/Users/ethanholda/Sites/gam2/lib/web/application.py", line 233, in handle
    return self._delegate(fn, self.fvars, args)
  File "/Users/ethanholda/Sites/gam2/lib/web/application.py", line 412, in _delegate
    return handle_class(cls)
  File "/Users/ethanholda/Sites/gam2/lib/web/application.py", line 387, in handle_class
    return tocall(*args)
TypeError: GET() takes at most 2 arguments (3 given)

 
2011-03-01 16:53:53,927 127.0.0.1       |INFO| ---------- GET / -------------------------------------------------------------------------- <controller.py:32>
2011-03-01 16:53:53,928 127.0.0.1       |INFO| SESSION: <Storage {'ip': u'127.0.0.1', 'session_id': 'f4da8a05a7c9c6626ae97c8f109f7602685d952d', '_changed': False}>  <controller.py:42>
2011-03-01 16:53:53: (mod_fastcgi.c.2701) FastCGI-stderr: Traceback (most recent call last):
  File "/Users/ethanholda/Sites/gam2/lib/web/application.py", line 242, in process
    return self.handle()
  File "/Users/ethanholda/Sites/gam2/lib/web/application.py", line 233, in handle
    return self._delegate(fn, self.fvars, args)
  File "/Users/ethanholda/Sites/gam2/lib/web/application.py", line 412, in _delegate
    return handle_class(cls)
  File "/Users/ethanholda/Sites/gam2/lib/web/application.py", line 387, in handle_class
    return tocall(*args)
TypeError: GET() takes at most 2 arguments (3 given)

 
2011-03-01 16:54:04: (server.c.1396) [note] graceful shutdown started 
2011-03-01 16:54:05: (server.c.1512) server stopped by UID = 501 PID = 430 
2011-03-01 16:54:07: (log.c.166) server started 
2011-03-01 16:54:07,461 X.X.X.X         |INFO| |||||||||||||||||||||||||||||||||||| SERVER START ||||||||||||||||||||||||||||||||||||||||||| <main.py:33>
2011-03-01 16:54:07,468 X.X.X.X         |INFO| Debug: True <main.py:36>
2011-03-01 16:54:07,468 X.X.X.X         |INFO| CONFIG: {'instance': 'GAM2', 'beanstalk': {'port': 11238, 'address': '0.0.0.0'}, 'memcache': {'port': 11222, 'address': '0.0.0.0'}, 'database': {'host': 'localhost', 'password': 'ringwrathes', 'db': 'gam2', 'user': 'root', 'dbn': 'mysql'}, 'default_host': 'http://ec2-204-236-198-80.compute-1.amazonaws.com/', 'email': {'username': 'myimapaccount@gmail.com', 'host': 'smtp.gmail.com', 'password': 'mypwd', 'port': 587}, 'dev': True} <main.py:37>
2011-03-01 16:54:14,423 127.0.0.1       |INFO| ---------- GET / -------------------------------------------------------------------------- <controller.py:32>
2011-03-01 16:54:14,428 127.0.0.1       |INFO| Connected to db: <lib.web.db.MySQLDB instance at 0x1016b9440> <controller.py:28>
2011-03-01 16:54:14,429 127.0.0.1       |INFO| SESSION: <Storage {'ip': u'127.0.0.1', 'session_id': 'f4da8a05a7c9c6626ae97c8f109f7602685d952d', '_changed': False}>  <controller.py:42>
2011-03-01 16:54:15,258 127.0.0.1       |INFO| 200: text/html (main) <controller.py:108>
2011-03-01 16:55:32: (log.c.166) server started 
2011-03-01 16:55:34,680 127.0.0.1       |INFO| ---------- GET / -------------------------------------------------------------------------- <controller.py:32>
2011-03-01 16:55:34,681 127.0.0.1       |INFO| SESSION: <Storage {'ip': u'127.0.0.1', 'session_id': 'f4da8a05a7c9c6626ae97c8f109f7602685d952d', '_changed': False}>  <controller.py:42>
2011-03-01 16:55:34,681 127.0.0.1       |INFO| 200: text/html (main) <controller.py:108>
2011-03-01 16:55:35,932 127.0.0.1       |INFO| ---------- GET / -------------------------------------------------------------------------- <controller.py:32>
2011-03-01 16:55:35,933 127.0.0.1       |INFO| SESSION: <Storage {'ip': u'127.0.0.1', 'session_id': 'f4da8a05a7c9c6626ae97c8f109f7602685d952d', '_changed': False}>  <controller.py:42>
2011-03-01 16:55:35,933 127.0.0.1       |INFO| 200: text/html (main) <controller.py:108>
2011-03-01 16:55:35: (mod_fastcgi.c.2568) unexpected end-of-file (perhaps the fastcgi process died): pid: 0 socket: unix:/tmp/fastcgi.socket-0 
2011-03-01 16:55:35: (mod_fastcgi.c.3356) response not received, request sent: 1105 on socket: unix:/tmp/fastcgi.socket-0 for /main.py?, closing connection 
2011-03-01 16:55:36: (mod_fastcgi.c.2568) unexpected end-of-file (perhaps the fastcgi process died): pid: 0 socket: unix:/tmp/fastcgi.socket-0 
2011-03-01 16:55:36: (mod_fastcgi.c.3371) response already sent out, but backend returned error on socket: unix:/tmp/fastcgi.socket-0 for /main.py?, terminating connection 
2011-03-01 16:55:39: (log.c.166) server started 
2011-03-01 16:56:00,097 127.0.0.1       |INFO| ---------- GET / -------------------------------------------------------------------------- <controller.py:32>
2011-03-01 16:56:00,097 127.0.0.1       |INFO| SESSION: <Storage {'ip': u'127.0.0.1', 'session_id': 'f4da8a05a7c9c6626ae97c8f109f7602685d952d', '_changed': False}>  <controller.py:42>
2011-03-01 16:56:00,098 127.0.0.1       |INFO| 200: text/html (main) <controller.py:108>
2011-03-01 16:56:01,847 127.0.0.1       |INFO| ---------- GET / -------------------------------------------------------------------------- <controller.py:32>
2011-03-01 16:56:01,847 127.0.0.1       |INFO| SESSION: <Storage {'ip': u'127.0.0.1', 'session_id': 'f4da8a05a7c9c6626ae97c8f109f7602685d952d', '_changed': False}>  <controller.py:42>
2011-03-01 16:56:01,847 127.0.0.1       |INFO| 200: text/html (main) <controller.py:108>
2011-03-01 16:56:02,877 127.0.0.1       |INFO| ---------- GET / -------------------------------------------------------------------------- <controller.py:32>
2011-03-01 16:56:02,878 127.0.0.1       |INFO| SESSION: <Storage {'ip': u'127.0.0.1', 'session_id': 'f4da8a05a7c9c6626ae97c8f109f7602685d952d', '_changed': False}>  <controller.py:42>
2011-03-01 16:56:02,878 127.0.0.1       |INFO| 200: text/html (main) <controller.py:108>
2011-03-01 16:56:03: (mod_fastcgi.c.2568) unexpected end-of-file (perhaps the fastcgi process died): pid: 0 socket: unix:/tmp/fastcgi.socket-0 
2011-03-01 16:56:03: (mod_fastcgi.c.3371) response already sent out, but backend returned error on socket: unix:/tmp/fastcgi.socket-0 for /main.py?, terminating connection 
2011-03-01 16:57:31: (server.c.1396) [note] graceful shutdown started 
2011-03-01 16:57:31: (server.c.1512) server stopped by UID = 501 PID = 430 
2011-03-01 16:57:34: (log.c.166) server started 
2011-03-01 16:57:41: (server.c.1396) [note] graceful shutdown started 
2011-03-01 16:57:50: (server.c.1512) server stopped by UID = 501 PID = 430 
2011-03-01 16:57:56: (log.c.166) server started 
2011-03-01 16:59:30: (server.c.1396) [note] graceful shutdown started 
2011-03-01 16:59:30: (server.c.1512) server stopped by UID = 501 PID = 430 
2011-03-01 16:59:33: (log.c.166) server started 
2011-03-01 16:59:53,020 127.0.0.1       |INFO| ---------- GET / -------------------------------------------------------------------------- <controller.py:32>
2011-03-01 16:59:53,021 127.0.0.1       |INFO| SESSION: <Storage {'ip': u'127.0.0.1', 'session_id': 'f4da8a05a7c9c6626ae97c8f109f7602685d952d', '_changed': False}>  <controller.py:42>
2011-03-01 16:59:53,021 127.0.0.1       |INFO| 200: text/html (main) <controller.py:108>
2011-03-01 17:02:58,831 127.0.0.1       |INFO| ---------- GET / -------------------------------------------------------------------------- <controller.py:32>
2011-03-01 17:02:58,832 127.0.0.1       |INFO| SESSION: <Storage {'ip': u'127.0.0.1', 'session_id': 'f4da8a05a7c9c6626ae97c8f109f7602685d952d', '_changed': False}>  <controller.py:42>
2011-03-01 17:02:58,832 127.0.0.1       |INFO| 200: text/html (main) <controller.py:108>
2011-03-01 17:03:02,516 127.0.0.1       |INFO| ---------- GET /register -------------------------------------------------------------------------- <controller.py:32>
2011-03-01 17:03:02,516 127.0.0.1       |INFO| SESSION: <Storage {'ip': u'127.0.0.1', 'session_id': 'f4da8a05a7c9c6626ae97c8f109f7602685d952d', '_changed': False}>  <controller.py:42>
2011-03-01 17:03:02,517 127.0.0.1       |INFO| 200: text/html (register) <controller.py:108>
2011-03-01 17:03:14,320 127.0.0.1       |INFO| ---------- GET /login -------------------------------------------------------------------------- <controller.py:32>
2011-03-01 17:03:14,320 127.0.0.1       |INFO| SESSION: <Storage {'ip': u'127.0.0.1', 'session_id': 'f4da8a05a7c9c6626ae97c8f109f7602685d952d', '_changed': False}>  <controller.py:42>
2011-03-01 17:03:14,320 127.0.0.1       |INFO| 200: text/html (login) <controller.py:108>
2011-03-01 17:03:17,820 127.0.0.1       |INFO| ---------- GET /blog -------------------------------------------------------------------------- <controller.py:32>
2011-03-01 17:03:17,820 127.0.0.1       |INFO| SESSION: <Storage {'ip': u'127.0.0.1', 'session_id': 'f4da8a05a7c9c6626ae97c8f109f7602685d952d', '_changed': False}>  <controller.py:42>
2011-03-01 17:03:17,820 127.0.0.1       |INFO| 200: text/html (blog) <controller.py:108>
2011-03-01 17:03:17: (mod_fastcgi.c.2701) FastCGI-stderr: Traceback (most recent call last):
  File "/Users/ethanholda/Sites/gam2/lib/web/application.py", line 242, in process
    return self.handle()
  File "/Users/ethanholda/Sites/gam2/lib/web/application.py", line 233, in handle
    return self._delegate(fn, self.fvars, args)
  File "/Users/ethanholda/Sites/gam2/lib/web/application.py", line 412, in _delegate
    return handle_class(cls)
  File "/Users/ethanholda/Sites/gam2/lib/web/application.py", line 387, in handle_class
    return tocall(*args)
  File "/Users/ethanholda/Sites/gam2/controllers/home.py", line 6, in GET
    return self.render(action)
  File "/Users/ethanholda/Sites/gam2/framework/controller.py", line 109, in render
    return (renderer[template_name + "." + suffix](template_values)).encode('utf-8')
  File "/Users/ethanholda/Sites/gam2/lib/web/contrib/template.py", line 99, in __getitem__
    t = self._lookup.get_template(name)
  File "lib/jinja2/environment.py", line 430, in get_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "lib/jinja2/loaders.py", line 91, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "lib/jinja2/loaders.py", line 131, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: blog.html

 
2011-03-01 17:04:24,038 127.0.0.1       |INFO| ---------- GET /login -------------------------------------------------------------------------- <controller.py:32>
2011-03-01 17:04:24,038 127.0.0.1       |INFO| SESSION: <Storage {'ip': u'127.0.0.1', 'session_id': 'f4da8a05a7c9c6626ae97c8f109f7602685d952d', '_changed': False}>  <controller.py:42>
2011-03-01 17:04:24,038 127.0.0.1       |INFO| 200: text/html (login) <controller.py:108>
2011-03-01 17:04:27,635 127.0.0.1       |INFO| ---------- GET /about -------------------------------------------------------------------------- <controller.py:32>
2011-03-01 17:04:27,635 127.0.0.1       |INFO| SESSION: <Storage {'ip': u'127.0.0.1', 'session_id': 'f4da8a05a7c9c6626ae97c8f109f7602685d952d', '_changed': False}>  <controller.py:42>
2011-03-01 17:04:27,636 127.0.0.1       |INFO| 200: text/html (about) <controller.py:108>
2011-03-01 17:04:29,829 127.0.0.1       |INFO| ---------- GET /blog -------------------------------------------------------------------------- <controller.py:32>
2011-03-01 17:04:29,829 127.0.0.1       |INFO| SESSION: <Storage {'ip': u'127.0.0.1', 'session_id': 'f4da8a05a7c9c6626ae97c8f109f7602685d952d', '_changed': False}>  <controller.py:42>
2011-03-01 17:04:29,829 127.0.0.1       |INFO| 200: text/html (blog) <controller.py:108>
2011-03-01 17:04:29: (mod_fastcgi.c.2701) FastCGI-stderr: Traceback (most recent call last):
  File "/Users/ethanholda/Sites/gam2/lib/web/application.py", line 242, in process
    return self.handle()
  File "/Users/ethanholda/Sites/gam2/lib/web/application.py", line 233, in handle
    return self._delegate(fn, self.fvars, args)
  File "/Users/ethanholda/Sites/gam2/lib/web/application.py", line 412, in _delegate
    return handle_class(cls)
  File "/Users/ethanholda/Sites/gam2/lib/web/application.py", line 387, in handle_class
    return tocall(*args)
  File "/Users/ethanholda/Sites/gam2/controllers/home.py", line 6, in GET
    return self.render(action)
  File "/Users/ethanholda/Sites/gam2/framework/controller.py", line 109, in render
    return (renderer[template_name + "." + suffix](template_values)).encode('utf-8')
  File "/Users/ethanholda/Sites/gam2/lib/web/contrib/template.py", line 99, in __getitem__
    t = self._lookup.get_template(name)
  File "lib/jinja2/environment.py", line 430, in get_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "lib/jinja2/loaders.py", line 91, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "lib/jinja2/loaders.py", line 131, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: blog.html

 
2011-03-01 17:58:04: (server.c.1396) [note] graceful shutdown started 
2011-03-01 17:58:04: (server.c.1512) server stopped by UID = 501 PID = 430 
